[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = {version = "2.2.12", features = ["postgres"]}
dotenvy = "0.15.7"
actix-web = "4"
serde = {version = "1.0.219", features = ["derive"]}
